# syntax=docker/dockerfile:1

ARG DEVICE_PLATFORM=linux/arm64/v8

FROM --platform=$DEVICE_PLATFORM alpine AS model-image

ADD ./best-int8.tflite      /models/best-int8.tflite
ADD ./labels.txt     /models/labels.txt

# When run, just show what models we have
CMD ["/bin/ls", "/models"]