version: '3.3'

services:
  object-detector-python:
    image: acap4-object-detector-python
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "100k"
    environment:
      - PYTHONUNBUFFERED=1
      - INFERENCE_HOST=unix:///tmp/acap-runtime.sock
      - INFERENCE_PORT=0
      - MODEL_PATH=/models/vehicle_detector12n.tflite
      - OBJECT_LIST_PATH=/models/labels.txt
    volumes:
      - acap_dl-models:/models:ro
      - /tmp:/output
      - inference-server:/tmp

  inference-server:
    image: axisecp/acap-runtime:2.0.0
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "100k"
    entrypoint:
      - /opt/app/acap_runtime/acapruntime
      - -m
      - /models/vehicle_detector12n.tflite
      - -j
      - artpec8
    volumes:
      - acap_dl-models:/models:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /run/parhand/parhandsocket:/run/parhand/parhandsocket
      - /usr/lib:/usr/lib
      - /usr/bin:/usr/bin
      - inference-server:/tmp

  acap_dl-models:
    image: my-yolo-model
    volumes:
      - acap_dl-models:/models

volumes:
  acap_dl-models: {}
  inference-server: {}
